### ISSUE TITLE
さくらインターネットのクーポンほしい人いません？

### ISSUE THREAD

**Issue by euglena1215** [kure-kosen/QnA-Issues#10]
@kure-kosen/all-member 

* さくらのクラウド 20000円分(3ヶ月間有効)
* さくらのVPS 初期費用最大5000円引き

クーポンをたくさんもらった(持って帰った)ので欲しい人いたら連絡ください。

パッと思いつく利用例

* さくらのクラウド使って36コア/メモリ224GBのモンスタースペックで機械学習ぶん回してみたい
(50時間くらいは使える)
* さくらのクラウド使ってISUCONみたいなサーバを立ててから行うコンテストの練習をしたい
* さくらのVPS使ってマイクラサーバが欲しい
* さくらのVPS使って自分のポートフォリオ的なサイトを作りたい

などなど

**Comment by kobakazu0429** [comment]
@euglena1215 
vpsのクーポン欲しいです！

**Comment by euglena1215** [comment]
@kobakazu10 
おっけ！何らかの形で送る！
