### ISSUE TITLE
モータドライバのリファレンス電圧

### ISSUE THREAD

**Issue by srpkdyy** [kure-kosen/QnA-Issues#2]
モータドライバ**AE-DRV8832**を使ってArduinoからモータを動かしたいのですが、
8番ピンのリファレンス電圧出力というのがわかりません。
上手く使えば、7番ピンの設定電圧にInputできるらしいのですが、使い方がわかりません。
分かる方、いらしたら教えてください。

**[DRV8832のデータシート](http://akizukidenshi.com/download/ds/akizuki/AE-drv8832_a.pdf)**

**Comment by chanyou0311** [comment]
@srpkdyy 
Vref電圧はWikipediaが簡潔に説明してくれているよ。

> 基準電圧回路（きじゅんでんあつかいろ、voltage reference circuit、Vref）とは、電源電圧や温度、素子ばらつきによらずに一定の電圧を出力する電子回路である。
[基準電圧回路 - Wikipedia](https://ja.wikipedia.org/wiki/%E5%9F%BA%E6%BA%96%E9%9B%BB%E5%9C%A7%E5%9B%9E%E8%B7%AF)

それで、7番ピンって要するに、出力電圧を決める役割のピンだから、出力電圧に一定に保ちたいのであれば、8番ピンの一定の電圧をうまい具合分圧して、7番ピンに入れてね、ということではないかと思います！

**Comment by chanyou0311** [comment]
これ解決しました？

**Comment by srpkdyy** [comment]
@chanyou0311 
まだ解決はしていませんが、なんとかやってみます
