### ISSUE TITLE
yarnやnpmのバージョン競合は発生しないのか

### ISSUE THREAD

**Issue by chanyou0311** [kure-kosen/QnA-Issues#3]
@kure-kosen/all-member 
Node.jsのパッケージ管理ツールでyarnやnpmがありますが、これらを使ってインストールしたパッケージは他と競合することはないのですか？
Pythonならpipでパッケージ管理しますが、プロジェクトごとに仮想環境を作って、必要以外のパッケージを入れないようにしますが、Node.jsだとそのあたりどのようにされてるのでしょうか？

**Comment by chanyou0311** [comment]
package.jsonあたりがキーとなるのかな

**Comment by euglena1215** [comment]
nodenvを使ってnodeのバージョンを指定、
yarn.lock(≒Gemfile.lock)でパッケージのバージョン指定、
インストールしたものは/node_modules配下に置いてプロジェクト内で完結させる、
という感じではないでしょうか。
yarnがいいのかnpmがいいのかは知らん

**Comment by chanyou0311** [comment]
nodenvたるものがあるんだね
色々といじって遊んでみます

ありがとうございました。
