### ISSUE TITLE
Rubyのメソッドの返り値にreturnを使うのは邪道なんですか

### ISSUE THREAD

**Issue by chanyou0311** [kure-kosen/QnA-Issues#4]
@kure-kosen/all-member 
Ruby on Rails 5.1のtutorialで勉強をしています。
Rubyのメソッドは最後に実行した式の値を返り値として使うとのことですが、returnで明示したほうが可読性高まると思いました。
Ruby使っている方はreturn書かないのが主流なのでしょうか。
それとも、規模によってreturnを書いたり書かなかったり、あるいは実はreturn書くのが主流だったりするのでしょうか。

**Comment by euglena1215** [comment]
原則としてはreturnは書かない方針だと思う。
要因としては
* 単純に'return'の文字数分タイプ数が増える
* 慣れればそんなに可読性変わらない気がする？(他の言語からだと変な感じがするかもしれないけど)

ただ早期returnでreturnを使うことはちょいちょいあるかな。
こんな感じで
```ruby
def hoge(foo = nil)
  return 'foo: nil' unless foo
  
  "foo: #{foo}"
end
```

**Comment by Gurrium** [comment]
@chanyou0311   
return書いてるのはほぼ見ないですねー

ただ
```ruby
def hoge_method(fuga)
  if fuga == 'piyo'
    bar = fuga
    return
  end

  bar = ''
end
```
みたいな書き方をすることはあります

って新谷さんが言ってます

**Comment by euglena1215** [comment]
> Ruby on Rails 5.1のtutorialで勉強をしています。
> Rubyのメソッドは最後に実行した式の値を返り値として使うとのことですが、returnで明示したほうが可読性高まると思いました。

ちなみにどんなコードをみてそれを思ったの？

**Comment by euglena1215** [comment]
@taira120 
```ruby
def hoge_method(fuga)
  if fuga == 'piyo'
    bar = fuga
    return
  end

  bar = ''
end
```
上のメソッドって下のメソッドと等価だよね？
```ruby
def hoge_method(fuga)
  fuga == 'piyo' ? nil : ''
end
```

`return` は`return`を処理するまでに最後に評価した値を返すのではなく、
`return nil`と等価なので注意！

**Comment by Gurrium** [comment]
@euglena1215  
返り値に意味はなくてただ代入の処理だけをするメソッドのつもりだったんですけど、それにしても

```ruby
def hoge_method(fuga)
  bar = ''

  bar = fuga if fuga == 'piyo'
  # if fuga == 'piyo'
    # bar = fuga
  # end
end
```

のほうがきれいな感じなので微妙な例でしたね

**Comment by chanyou0311** [comment]
@euglena1215 
[ここ](https://railstutorial.jp/chapters/rails_flavored_ruby?version=5.1#code-annotated_title_helper)のこのコードのことでした。

```ruby
def full_title(page_title = '')
  base_title = "Ruby on Rails Tutorial Sample App"
  if page_title.empty?
    base_title
  else 
    page_title + " | " + base_title
 end
end
```

なんとなく感覚がわかりました。ありがとうございました。

**Comment by euglena1215** [comment]
後置ifについて補足！！！

Rubyには後置ifっていう構文があるんだけど、
後置ifで評価した結果をreturnで返そうとすると思ってた結果と違うものが返ってきて困るというのがよくあるハマりポイントかも。

```ruby
[1] pry(main)> def hoge
[1] pry(main)*   1
[1] pry(main)*   2 if false
[1] pry(main)* end
=> :hoge
[2] pry(main)> hoge
=> nil
```

ifの条件文がfalseだったらifの前の処理(`2`)を評価せずに`nil`を返すという仕組みになっている。

ので、後置ifは

- 式ではなく文として取り扱う(返り値を使った処理を書かない)
- 早期returnとして使い、メソッドの最後の処理としては使わない

のがbetterかも。
