### ISSUE TITLE
githubでブランチの切り方について

### ISSUE THREAD

**Issue by kobakazu0429** [kure-kosen/QnA-Issues#6]
自分の中で
master：リリース可能、もしくは現在リリースしているもの。基本developからのみマージをうけつけ直接コミットしない
develop：開発中のもの
feature：developからさらに切って細かく開発
って感じになってるんですけど合ってますかね？
いまいちチーム開発での使い方が分かってません。 
@kure-kosen/all-member

**Comment by euglena1215** [comment]
@kobakazu10 
だいたい合ってると思う！
1つのfeatureブランチで名前の通り1つの機能/特徴を実装するってイメージかな。
あとバグを修正するときに使うfixもあったりするね。

developからfeatureブランチを切って実装して、実装が終わるとdevelopにマージ、を数回繰り返す。
まとまった機能が実装された段階でdevelopをmasterにマージしてリリース、って流れだと思う。

ただ、最近のwebサービス開発は「とりあえずリリースしちゃってマズそうであれば戻し(Revert)ちゃえ」ってところも増えてきててdevelopが存在しない企業もあったりするよ。
だから結局のところ自分達の開発手法に合わせたブランチの切り方をすればそれが正解なので
既存のに絶対合わせないといけないわけではないよ！！
(とりあえず既存に乗っかってみてから考えるのはよくやる)

**Comment by kobakazu0429** [comment]
@euglena1215 
基本developに一つ機能を加えるたびにfeatureで切るってことですよね！
ありがとうございます。

**Comment by kobakazu0429** [comment]
@kure-kosen/all-member 
一つのファイルを複数人で編集するときは同じブランチでいいんですか？
それとも一人ずつ新しくブランチ切りますか？

**Comment by euglena1215** [comment]
@kobakazu10 
> 一つのファイルを複数人で編集するときは同じブランチでいいんですか？
それとも一人ずつ新しくブランチ切りますか？

基本的には1つのブランチは1人が対応する感じだね。
じゃないとコードの不整合が起こる可能性があるからね。

コードの不整合ってのは
```ruby
def hoge
  x = 10
  y = 100
  puts "y: #{y}"  # => y: 100
end
```
例えば上のようなメソッドがあったとして、AさんとBさんが上を元に修正を加えたとする。
(+は追加、-は削除という意味)

Aさんの修正ではxは使われてなかったのでxも表示させるようにした。
```ruby
def hoge
  x = 10
  y = 100
+  puts "x: #{x}, y: #{y}"  # => x: 10, y: 100
-  puts "y: #{y}"
end
```

Bさんの修正ではxは使われてなかったのでxは削除した。
```ruby
def hoge
- x = 10
  y = 100
  puts "y: #{y}" # => y: 100 
end
```

2人が修正したことによって以下のようなエラーが発生するようになった。
```ruby
def hoge
- x = 10
  y = 100
+  puts "x: #{x}, y: #{y}" # => ERROR: x is not defined!!!
-  puts "y: #{y}"
end
```

同じブランチで複数人が(特に同じ時間帯に)作業するとどのタイミングで混ざるか分からないからこんなミスを生んでしまう可能性がある。
(このくらい小さければまぁ起こらないだろうけどね)
ブランチが分かれてたらそれぞれが明示的にPRを出すので混ざるタイミングが明確だし、バグが生まれてないかレビューできるからブランチは人ごとで切った方がいいという話でした。

**Comment by kobakazu0429** [comment]
了解しました。
解決しました。
ありがとうございます。
